name: pauto
description: pinokio auto script
version: 1.0.0
homepage: https://github.com/yuzumone/pauto

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.3.1
  http: ^0.13.5
  spotify: ^0.7.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
